class Error(Exception):
	pass

class TestError(Error):
	pass